# Generated by Django 5.1.6 on 2025-02-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
