# Generated by Django 5.1.6 on 2025-02-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_alter_ticket_flight_alter_ticket_order"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="flight",
            constraint=models.UniqueConstraint(
                fields=("route", "airplane", "departure_time", "arrival_time"),
                name="unique_flight_per_time",
            ),
        ),
    ]
