# Generated by Django 5.1.6 on 2025-02-24 13:40

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_flight_unique_flight_per_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=airport.models.airplane_custom_path
            ),
        ),
    ]
