# Generated by Django 5.1.6 on 2025-02-27 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0006_airplane_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="airplane",
            name="name",
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name="airplanetype",
            name="name",
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name="airport",
            name="city",
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name="airport",
            name="country",
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name="airport",
            name="name",
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name="crew",
            name="first_name",
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name="crew",
            name="last_name",
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name="crew",
            name="role",
            field=models.CharField(
                choices=[
                    ("CAPTAIN", "Pilot in Command"),
                    ("SECOND_PILOT", "Co-Pilot"),
                    ("STEWARD", "Flight Attendant"),
                    ("OTHER", "Other staff"),
                ],
                max_length=63,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_routes",
                to="airport.airport",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="airport.airport",
            ),
        ),
    ]
